name: Build, Sign, and Release Firefox Extension

on:
  push:
    branches:
      - main  
permissions:
  contents: write
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  

      - name: Install web-ext
        run: npm install --global web-ext

      - name: Build and sign the extension
        run: web-ext sign --artifacts-dir ./artifacts --api-key ${{ secrets.AMO_JWT_ISSUER }} --api-secret ${{ secrets.AMO_JWT_SECRET }}
        env:
          WEB_EXT_API_KEY: ${{ secrets.JWT_ISSUER }}
          WEB_EXT_API_SECRET: ${{ secrets.JWT_SECRET }}
                
      - name: Find signed XPI file name
        id: find-xpi
        run: echo "::set-output name=xpi_name::$(ls ./artifacts/*.xpi)"
        
      - name: Create Tag
        run: |
          TAG_NAME="v$(date +'%Y.%m.%d.%H.%M.%S')"
          echo "Creating tag $TAG_NAME"
          git tag -a $TAG_NAME -m "Release version $TAG_NAME"
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload signed XPI as a release
        uses: softprops/action-gh-release@v1

        with:
          files: ${{ steps.find-xpi.outputs.xpi_name }}
          tag_name: ${{ steps.create-tag.outputs.TAG_NAME }}
          name: Release ${{ steps.create-tag.outputs.TAG_NAME }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
