name: Build, Sign, and Release Firefox Extension

on:
  push:
    branches:
      - main  
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  
      - name: Install dependencies
        run: npm install

      - name: Install web-ext
        run: npm install --global web-ext

      - name: Build and sign the extension
        run: web-ext sign --artifacts-dir ./artifacts --api-key ${{ secrets.AMO_JWT_ISSUER }} --api-secret ${{ secrets.AMO_JWT_SECRET }}
        env:
          WEB_EXT_API_KEY: ${{ secrets.JWT_ISSUER }}
          WEB_EXT_API_SECRET: ${{ secrets.JWT_SECRET }}
                
      - name: Find signed XPI file name
        id: find-xpi
        run: echo "::set-output name=xpi_name::$(ls ./artifacts/*.xpi)"
        
      - name: Upload signed XPI as a release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.find-xpi.outputs.xpi_name }}
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
